import { Tenant, Invoice, KpiTemplate, BscTemplate, AuditLog } from './types';

export const initialTenants: Tenant[] = [
  {
    id: 't1',
    name: 'FPT Software',
    registeredAt: '2026-01-15',
    packageType: 'Enterprise',
    employeeCount: 1250,
    status: 'active',
    adminName: 'Nguyễn Văn A',
    adminEmail: 'a.nguyen@fpt.com',
  },
  {
    id: 't2',
    name: 'Viettel Telecom',
    registeredAt: '2026-02-10',
    packageType: 'Enterprise',
    employeeCount: 3400,
    status: 'active',
    adminName: 'Trần Minh B',
    adminEmail: 'b.tran@viettel.vn',
  },
  {
    id: 't3',
    name: 'Masan Group',
    registeredAt: '2026-03-01',
    packageType: 'Growth',
    employeeCount: 450,
    status: 'active',
    adminName: 'Phạm Thị C',
    adminEmail: 'c.pham@masan.vn',
  },
  {
    id: 't4',
    name: 'VNG Corporation',
    registeredAt: '2026-03-12',
    packageType: 'Growth',
    employeeCount: 280,
    status: 'active',
    adminName: 'Lê Hoàng D',
    adminEmail: 'd.le@vng.com.vn',
  },
  {
    id: 't5',
    name: 'Techcombank',
    registeredAt: '2026-04-05',
    packageType: 'Enterprise',
    employeeCount: 1500,
    status: 'active',
    adminName: 'Hoàng Văn E',
    adminEmail: 'e.hoang@techcombank.com.vn',
  },
  {
    id: 't6',
    name: 'Giao Hàng Nhanh (GHN)',
    registeredAt: '2026-04-20',
    packageType: 'Growth',
    employeeCount: 320,
    status: 'active',
    adminName: 'Vũ Thị F',
    adminEmail: 'f.vu@ghn.vn',
  },
  {
    id: 't7',
    name: 'KiotViet',
    registeredAt: '2026-05-02',
    packageType: 'Starter',
    employeeCount: 45,
    status: 'active',
    adminName: 'Đặng Ngọc G',
    adminEmail: 'g.dang@kiotviet.com',
  },
  {
    id: 't8',
    name: 'Coolmate',
    registeredAt: '2026-05-18',
    packageType: 'Starter',
    employeeCount: 35,
    status: 'active',
    adminName: 'Ngô Quốc H',
    adminEmail: 'h.ngo@coolmate.me',
  },
  {
    id: 't9',
    name: 'Vinamilk',
    registeredAt: '2026-05-25',
    packageType: 'Enterprise',
    employeeCount: 890,
    status: 'locked',
    adminName: 'Đỗ Tiến I',
    adminEmail: 'i.do@vinamilk.com.vn',
  },
  {
    id: 't10',
    name: 'Hòa Phát Group',
    registeredAt: '2026-06-01',
    packageType: 'Growth',
    employeeCount: 120,
    status: 'locked',
    adminName: 'Bùi Quang J',
    adminEmail: 'j.bui@hoaphat.com.vn',
  },
];

export const initialInvoices: Invoice[] = [
  {
    id: 'inv1',
    invoiceCode: 'SKF-2026-001',
    tenantId: 't1',
    tenantName: 'FPT Software',
    packageType: 'Enterprise',
    cycle: 'yearly',
    amount: 180000000,
    paymentMethod: 'bank_transfer',
    status: 'success',
    createdAt: '2026-01-16 09:30',
  },
  {
    id: 'inv2',
    invoiceCode: 'SKF-2026-002',
    tenantId: 't2',
    tenantName: 'Viettel Telecom',
    packageType: 'Enterprise',
    cycle: 'yearly',
    amount: 180000000,
    paymentMethod: 'bank_transfer',
    status: 'success',
    createdAt: '2026-02-11 14:15',
  },
  {
    id: 'inv3',
    invoiceCode: 'SKF-2026-003',
    tenantId: 't3',
    tenantName: 'Masan Group',
    packageType: 'Growth',
    cycle: 'monthly',
    amount: 8500000,
    paymentMethod: 'vnpay',
    status: 'success',
    createdAt: '2026-03-01 10:00',
  },
  {
    id: 'inv4',
    invoiceCode: 'SKF-2026-004',
    tenantId: 't4',
    tenantName: 'VNG Corporation',
    packageType: 'Growth',
    cycle: 'yearly',
    amount: 90000000,
    paymentMethod: 'bank_transfer',
    status: 'success',
    createdAt: '2026-03-12 11:20',
  },
  {
    id: 'inv5',
    invoiceCode: 'SKF-2026-005',
    tenantId: 't5',
    tenantName: 'Techcombank',
    packageType: 'Enterprise',
    cycle: 'monthly',
    amount: 16500000,
    paymentMethod: 'bank_transfer',
    status: 'success',
    createdAt: '2026-04-05 16:45',
  },
  {
    id: 'inv6',
    invoiceCode: 'SKF-2026-006',
    tenantId: 't6',
    tenantName: 'Giao Hàng Nhanh (GHN)',
    packageType: 'Growth',
    cycle: 'monthly',
    amount: 8500000,
    paymentMethod: 'momo',
    status: 'success',
    createdAt: '2026-04-20 08:30',
  },
  {
    id: 'inv7',
    invoiceCode: 'SKF-2026-007',
    tenantId: 't7',
    tenantName: 'KiotViet',
    packageType: 'Starter',
    cycle: 'monthly',
    amount: 3500000,
    paymentMethod: 'momo',
    status: 'success',
    createdAt: '2026-05-02 09:00',
  },
  {
    id: 'inv8',
    invoiceCode: 'SKF-2026-008',
    tenantId: 't8',
    tenantName: 'Coolmate',
    packageType: 'Starter',
    cycle: 'yearly',
    amount: 36000000,
    paymentMethod: 'vnpay',
    status: 'success',
    createdAt: '2026-05-18 13:50',
  },
  {
    id: 'inv9',
    invoiceCode: 'SKF-2026-009',
    tenantId: 't9',
    tenantName: 'Vinamilk',
    packageType: 'Enterprise',
    cycle: 'yearly',
    amount: 180000000,
    paymentMethod: 'bank_transfer',
    status: 'failed',
    createdAt: '2026-05-25 10:15',
  },
  {
    id: 'inv10',
    invoiceCode: 'SKF-2026-010',
    tenantId: 't10',
    tenantName: 'Hòa Phát Group',
    packageType: 'Growth',
    cycle: 'monthly',
    amount: 8500000,
    paymentMethod: 'vnpay',
    status: 'pending',
    createdAt: '2026-06-01 11:00',
  },
  {
    id: 'inv11',
    invoiceCode: 'SKF-2026-011',
    tenantId: 't3',
    tenantName: 'Masan Group',
    packageType: 'Growth',
    cycle: 'monthly',
    amount: 8500000,
    paymentMethod: 'vnpay',
    status: 'success',
    createdAt: '2026-04-01 10:05',
  },
  {
    id: 'inv12',
    invoiceCode: 'SKF-2026-012',
    tenantId: 't5',
    tenantName: 'Techcombank',
    packageType: 'Enterprise',
    cycle: 'monthly',
    amount: 16500000,
    paymentMethod: 'bank_transfer',
    status: 'success',
    createdAt: '2026-05-05 16:50',
  },
  {
    id: 'inv13',
    invoiceCode: 'SKF-2026-013',
    tenantId: 't6',
    tenantName: 'Giao Hàng Nhanh (GHN)',
    packageType: 'Growth',
    cycle: 'monthly',
    amount: 8500000,
    paymentMethod: 'momo',
    status: 'success',
    createdAt: '2026-05-20 08:35',
  },
  {
    id: 'inv14',
    invoiceCode: 'SKF-2026-014',
    tenantId: 't7',
    tenantName: 'KiotViet',
    packageType: 'Starter',
    cycle: 'monthly',
    amount: 3500000,
    paymentMethod: 'momo',
    status: 'success',
    createdAt: '2026-06-02 09:10',
  },
  {
    id: 'inv15',
    invoiceCode: 'SKF-2026-015',
    tenantId: 't3',
    tenantName: 'Masan Group',
    packageType: 'Growth',
    cycle: 'monthly',
    amount: 8500000,
    paymentMethod: 'vnpay',
    status: 'success',
    createdAt: '2026-05-01 10:10',
  },
];

export const initialKpis: KpiTemplate[] = [
  {
    id: 'kpi1',
    department: 'Kinh doanh (Sales)',
    name: 'Doanh số bán hàng cá nhân/nhóm',
    target: 'Đạt 100% chỉ tiêu doanh số được giao',
    unit: 'VNĐ / Phần trăm',
    frequency: 'monthly',
    description: 'Đo lường tổng giá trị doanh thu mang về từ các hợp đồng ký kết thành công trong tháng.',
  },
  {
    id: 'kpi2',
    department: 'Kinh doanh (Sales)',
    name: 'Tỷ lệ chốt hợp đồng thành công (Conversion Rate)',
    target: 'Tối thiểu 15%',
    unit: 'Phần trăm (%)',
    frequency: 'monthly',
    description: 'Tỷ lệ giữa số lượng khách hàng ký hợp đồng thành công trên tổng số khách hàng tiếp cận tiềm năng.',
  },
  {
    id: 'kpi3',
    department: 'Marketing',
    name: 'Số lượng Lead chất lượng (MQL - Marketing Qualified Lead)',
    target: '1,500 Leads chất lượng',
    unit: 'MQLs',
    frequency: 'monthly',
    description: 'Số lượng khách hàng tiềm năng thu về từ các chiến dịch Marketing đã được lọc và đạt tiêu chuẩn liên hệ.',
  },
  {
    id: 'kpi4',
    department: 'Marketing',
    name: 'Chi phí trên mỗi khách hàng tiềm năng (CPL - Cost Per Lead)',
    target: 'Dưới 150,000 VNĐ',
    unit: 'VNĐ',
    frequency: 'monthly',
    description: 'Tổng ngân sách quảng cáo chia cho tổng số leads nhận được trong chiến dịch.',
  },
  {
    id: 'kpi5',
    department: 'Nhân sự (HR)',
    name: 'Thời gian tuyển dụng trung bình (Time to Hire)',
    target: 'Dưới 25 ngày',
    unit: 'Ngày',
    frequency: 'quarterly',
    description: 'Số ngày trung bình tính từ lúc phát sinh nhu cầu tuyển dụng đến lúc ứng viên chính thức đồng ý nhận việc.',
  },
  {
    id: 'kpi6',
    department: 'Nhân sự (HR)',
    name: 'Tỷ lệ nghỉ việc tự nguyện (Turnover Rate)',
    target: 'Dưới 4% một quý',
    unit: 'Phần trăm (%)',
    frequency: 'quarterly',
    description: 'Số lượng nhân viên tự nguyện nghỉ việc chia cho tổng số nhân sự trung bình trong quý.',
  },
  {
    id: 'kpi7',
    department: 'Công nghệ thông tin (IT)',
    name: 'Thời gian hoạt động hệ thống (System Uptime)',
    target: 'Đạt 99.9% uptime',
    unit: 'Phần trăm (%)',
    frequency: 'monthly',
    description: 'Đo lường mức độ sẵn sàng và ổn định hoạt động của các dịch vụ cloud/SaaS.',
  },
  {
    id: 'kpi8',
    department: 'Công nghệ thông tin (IT)',
    name: 'Số lượng lỗi bảo mật nghiêm trọng phát hiện',
    target: '0 lỗi nghiêm trọng (Critical)',
    unit: 'Lỗi',
    frequency: 'monthly',
    description: 'Tổng số lỗi bảo mật mức độ High hoặc Critical phát hiện qua kiểm thử xâm nhập hoặc quét mã nguồn định kỳ.',
  },
  {
    id: 'kpi9',
    department: 'Tài chính (Finance)',
    name: 'Tỷ lệ nợ quá hạn (Overdue Invoices Rate)',
    target: 'Dưới 5%',
    unit: 'Phần trăm (%)',
    frequency: 'monthly',
    description: 'Tổng giá trị nợ phải thu quá hạn trên tổng số nợ phải thu trong kỳ thanh toán.',
  },
];

export const initialBscs: BscTemplate[] = [
  {
    id: 'bsc1',
    industry: 'Phát triển Phần mềm & CNTT',
    perspective: 'Financial',
    objective: 'Tối ưu hóa MRR/ARR và giá trị trọn đời của khách hàng (LTV)',
    description: 'Tập trung tăng trưởng doanh số định kỳ từ các gói subscription phần mềm và cải thiện doanh số bán thêm (upsell).',
  },
  {
    id: 'bsc2',
    industry: 'Phát triển Phần mềm & CNTT',
    perspective: 'Customer',
    objective: 'Tăng mức độ hài lòng khách hàng thông qua trải nghiệm UX/UI và hỗ trợ kỹ thuật',
    description: 'Nâng điểm NPS (Net Promoter Score) lên >45 và giảm tỷ lệ huỷ bỏ dịch vụ (Churn Rate) xuống dưới 2% hàng tháng.',
  },
  {
    id: 'bsc3',
    industry: 'Phát triển Phần mềm & CNTT',
    perspective: 'Internal Process',
    objective: 'Nâng cao chất lượng code và tốc độ bàn giao tính năng (Agile CI/CD)',
    description: 'Giảm thời gian chu kỳ phát hành tính năng lớn xuống còn 2 tuần và giảm tỷ lệ bug thoát ra môi trường Production.',
  },
  {
    id: 'bsc4',
    industry: 'Phát triển Phần mềm & CNTT',
    perspective: 'Learning & Growth',
    objective: 'Phát triển năng lực lập trình và chứng chỉ Cloud cho đội ngũ Dev/Ops',
    description: 'Đảm bảo ít nhất 70% kỹ sư có chứng chỉ AWS/Azure/GCP và hoàn thành khoá huấn luyện nâng cao kỹ năng xử lý hệ thống tải cao.',
  },
  {
    id: 'bsc5',
    industry: 'Bán lẻ & Thương mại điện tử',
    perspective: 'Financial',
    objective: 'Tăng biên lợi nhuận gộp và vòng quay hàng tồn kho',
    description: 'Tối ưu hoá chuỗi cung ứng, đàm phán giá nhập kho và tăng hiệu suất bán hàng đa kênh (Omnichannel sales).',
  },
  {
    id: 'bsc6',
    industry: 'Bán lẻ & Thương mại điện tử',
    perspective: 'Customer',
    objective: 'Tối ưu hóa tỷ lệ khách hàng mua lại (Retention Rate)',
    description: 'Cải thiện hệ thống chăm sóc khách hàng thân thiết, ưu đãi cá nhân hoá thông qua Loyalty App.',
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'log1',
    adminName: 'Supreme Admin',
    action: 'Cập nhật trạng thái Tenant',
    target: 'Vinamilk (locked)',
    timestamp: '2026-06-29 10:24',
    ipAddress: '192.168.1.45',
  },
  {
    id: 'log2',
    adminName: 'Supreme Admin',
    action: 'Tạo mới KPI mẫu',
    target: 'Doanh số bán hàng cá nhân/nhóm (Sales)',
    timestamp: '2026-06-28 15:40',
    ipAddress: '115.79.130.4',
  },
  {
    id: 'log3',
    adminName: 'System Monitor',
    action: 'Sao lưu cơ sở dữ liệu tự động',
    target: 'SkillForge_DB_Backup_20260628',
    timestamp: '2026-06-28 00:00',
    ipAddress: '10.0.0.12',
  },
  {
    id: 'log4',
    adminName: 'Supreme Admin',
    action: 'Duyệt kích hoạt gói dịch vụ',
    target: 'FPT Software (Enterprise)',
    timestamp: '2026-06-27 09:12',
    ipAddress: '192.168.1.45',
  },
];
